## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [7]:
pos_index = y == 1
neg_index = y == 0

x_pos, y_pos = X[pos_index], y[pos_index]
x_neg, y_neg = X[neg_index], y[neg_index]

x_pos_train, x_pos_test, y_pos_train, y_pos_test= train_test_split(x_pos, y_pos, test_size=10)
x_neg_train, x_neg_test, y_neg_train, y_neg_test= train_test_split(x_neg, y_neg, test_size=10)

x_train = np.vstack((x_pos_train, x_neg_train))
x_test = np.vstack((x_pos_test, x_neg_test))
y_train = np.hstack((y_pos_train, y_neg_train))
y_test = np.hstack((y_pos_test, y_neg_test))

In [10]:
print(f"x_train.shape:{x_train.shape}\n"
      f"x_test.shape:{x_test.shape}\n"
      f"y_train.shape:{y_train.shape}\n"
      f"y_test.shape:{y_test.shape}\n"
     )

print('x_test', x_test)
print('y_test', y_test)

x_train.shape:(180, 5)
x_test.shape:(20, 5)
y_train.shape:(180,)
y_test.shape:(20,)

x_test [[ 70  71  72  73  74]
 [150 151 152 153 154]
 [ 95  96  97  98  99]
 [185 186 187 188 189]
 [115 116 117 118 119]
 [125 126 127 128 129]
 [ 90  91  92  93  94]
 [ 60  61  62  63  64]
 [140 141 142 143 144]
 [165 166 167 168 169]
 [325 326 327 328 329]
 [630 631 632 633 634]
 [570 571 572 573 574]
 [955 956 957 958 959]
 [300 301 302 303 304]
 [515 516 517 518 519]
 [595 596 597 598 599]
 [575 576 577 578 579]
 [660 661 662 663 664]
 [925 926 927 928 929]]
y_test [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
import pandas as pd
print("y_train")
print(pd.Series(y_train).value_counts())
print("--"*10)
print("y_test")
print(pd.Series(y_test).value_counts())

y_train
0.0    150
1.0     30
dtype: int64
--------------------
y_test
0.0    10
1.0    10
dtype: int64
